//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbird.Plugins.Plunet.DataAdmin30Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://API.Integration/", ConfigurationName="Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30")]
    public interface DataAdmin30
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableServicesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableServicesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServiceListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.ServiceListResult> getAvailableServicesAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableCountriesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableCountriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CountryListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CountryListResult> getAvailableCountriesAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableDocumentTemplatesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableDocumentTemplatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringArrayResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringArrayResult> getAvailableDocumentTemplatesAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableLanguagesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableLanguagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="LanguageListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.LanguageListResult> getAvailableLanguagesAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getDomesticCurrencyRequest", ReplyAction="http://API.Integration/DataAdmin30/getDomesticCurrencyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringResult> getDomesticCurrencyAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getSystemCurrenciesRequest", ReplyAction="http://API.Integration/DataAdmin30/getSystemCurrenciesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CurrencyListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CurrencyList> getSystemCurrenciesAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getCompanyCodeListRequest", ReplyAction="http://API.Integration/DataAdmin30/getCompanyCodeListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompanyCodeListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CompanyCodeListResult> getCompanyCodeListAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getListOfRegisteredCallbacksRequest", ReplyAction="http://API.Integration/DataAdmin30/getListOfRegisteredCallbacksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CallbackListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CallbackListResult> getListOfRegisteredCallbacksAsync(string UUID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class ServiceListResult : Result
    {
        
        private Service[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Service[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Service
    {
        
        private string abbreviationField;
        
        private int idField;
        
        private string jobCategoryField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string jobCategory
        {
            get
            {
                return this.jobCategoryField;
            }
            set
            {
                this.jobCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Country
    {
        
        private int idField;
        
        private string isoCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isoCode
        {
            get
            {
                return this.isoCodeField;
            }
            set
            {
                this.isoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CompanyCode
    {
        
        private int companyCodeIDField;
        
        private bool companyCodeRightsField;
        
        private string description_LongField;
        
        private string description_ShortField;
        
        private bool isCompanyCodeInvoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int companyCodeID
        {
            get
            {
                return this.companyCodeIDField;
            }
            set
            {
                this.companyCodeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool companyCodeRights
        {
            get
            {
                return this.companyCodeRightsField;
            }
            set
            {
                this.companyCodeRightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description_Long
        {
            get
            {
                return this.description_LongField;
            }
            set
            {
                this.description_LongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description_Short
        {
            get
            {
                return this.description_ShortField;
            }
            set
            {
                this.description_ShortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isCompanyCodeInvoice
        {
            get
            {
                return this.isCompanyCodeInvoiceField;
            }
            set
            {
                this.isCompanyCodeInvoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Callback
    {
        
        private int benutzerIDField;
        
        private int callbackTypeField;
        
        private int dataServiceField;
        
        private int errorCountField;
        
        private int eventTypeField;
        
        private int mainIDField;
        
        private int objectTypeField;
        
        private string serverAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int benutzerID
        {
            get
            {
                return this.benutzerIDField;
            }
            set
            {
                this.benutzerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int callbackType
        {
            get
            {
                return this.callbackTypeField;
            }
            set
            {
                this.callbackTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dataService
        {
            get
            {
                return this.dataServiceField;
            }
            set
            {
                this.dataServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int errorCount
        {
            get
            {
                return this.errorCountField;
            }
            set
            {
                this.errorCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int eventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int mainID
        {
            get
            {
                return this.mainIDField;
            }
            set
            {
                this.mainIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int objectType
        {
            get
            {
                return this.objectTypeField;
            }
            set
            {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string serverAddress
        {
            get
            {
                return this.serverAddressField;
            }
            set
            {
                this.serverAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Currency
    {
        
        private int currencyIDField;
        
        private string descriptionField;
        
        private string isoCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int currencyID
        {
            get
            {
                return this.currencyIDField;
            }
            set
            {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string isoCode
        {
            get
            {
                return this.isoCodeField;
            }
            set
            {
                this.isoCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Language
    {
        
        private bool activeField;
        
        private bool favoriteField;
        
        private string folderNameField;
        
        private int idField;
        
        private string isoCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool favorite
        {
            get
            {
                return this.favoriteField;
            }
            set
            {
                this.favoriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string folderName
        {
            get
            {
                return this.folderNameField;
            }
            set
            {
                this.folderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isoCode
        {
            get
            {
                return this.isoCodeField;
            }
            set
            {
                this.isoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringArrayResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyCodeListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CallbackListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrencyList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageListResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Result
    {
        
        private int statusCodeField;
        
        private string statusCodeAlphanumericField;
        
        private string statusMessageField;
        
        private System.Nullable<int>[] warning_StatusCodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCodeAlphanumeric
        {
            get
            {
                return this.statusCodeAlphanumericField;
            }
            set
            {
                this.statusCodeAlphanumericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("warning_StatusCodeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int>[] warning_StatusCodeList
        {
            get
            {
                return this.warning_StatusCodeListField;
            }
            set
            {
                this.warning_StatusCodeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringResult : Result
    {
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringArrayResult : Result
    {
        
        private string[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CountryListResult : Result
    {
        
        private Country[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Country[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CompanyCodeListResult : Result
    {
        
        private CompanyCode[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public CompanyCode[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CallbackListResult : Result
    {
        
        private Callback[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Callback[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CurrencyList : Result
    {
        
        private Currency[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Currency[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class LanguageListResult : Result
    {
        
        private Language[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Language[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DataAdmin30Channel : Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DataAdmin30Client : System.ServiceModel.ClientBase<Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30>, Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataAdmin30Client(Uri url) : 
                base(DataAdmin30Client.GetDefaultBinding(), DataAdmin30Client.GetDefaultEndpointAddress(url.ToString().TrimEnd('/')))
        {
            this.Endpoint.Name = EndpointConfiguration.DataAdmin30Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(EndpointConfiguration endpointConfiguration, Uri url) : 
                base(DataAdmin30Client.GetBindingForEndpoint(endpointConfiguration), DataAdmin30Client.GetEndpointAddress(endpointConfiguration, url.ToString().TrimEnd('/')))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataAdmin30Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataAdmin30Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.ServiceListResult> getAvailableServicesAsync(string UUID, string languageCode)
        {
            return base.Channel.getAvailableServicesAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CountryListResult> getAvailableCountriesAsync(string UUID, string languageCode)
        {
            return base.Channel.getAvailableCountriesAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringArrayResult> getAvailableDocumentTemplatesAsync(string UUID)
        {
            return base.Channel.getAvailableDocumentTemplatesAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.LanguageListResult> getAvailableLanguagesAsync(string UUID, string languageCode)
        {
            return base.Channel.getAvailableLanguagesAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringResult> getDomesticCurrencyAsync(string UUID)
        {
            return base.Channel.getDomesticCurrencyAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CurrencyList> getSystemCurrenciesAsync(string UUID)
        {
            return base.Channel.getSystemCurrenciesAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CompanyCodeListResult> getCompanyCodeListAsync(string UUID)
        {
            return base.Channel.getCompanyCodeListAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CallbackListResult> getListOfRegisteredCallbacksAsync(string UUID)
        {
            return base.Channel.getListOfRegisteredCallbacksAsync(UUID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataAdmin30Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration, string url)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataAdmin30Port))
            {
                return new System.ServiceModel.EndpointAddress($"{url}/DataAdmin30");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataAdmin30Client.GetBindingForEndpoint(EndpointConfiguration.DataAdmin30Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress(string url)
        {
            return DataAdmin30Client.GetEndpointAddress(EndpointConfiguration.DataAdmin30Port, url);
        }
        
        public enum EndpointConfiguration
        {
            
            DataAdmin30Port,
        }
    }
}
