//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbird.Plugins.Plunet.DataCustomerContact30Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://API.Integration/", ConfigurationName="Blackbird.Plugins.Plunet.DataCustomerContact30Service.DataCustomerContact30")]
    public interface DataCustomerContact30
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/updateRequest", ReplyAction="http://API.Integration/DataCustomerContact30/updateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> updateAsync(string UUID, Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactIN CustomerContactIN, bool enableNullOrEmptyValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/insertRequest", ReplyAction="http://API.Integration/DataCustomerContact30/insertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> insertAsync(string UUID, int partnerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getStatusRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getStatusAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setStatusRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setStatusAsync(string UUID, int Status, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getAllContactObjectsRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getAllContactObjectsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CustomerContactListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactListResult> getAllContactObjectsAsync(string UUID, int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getCustomerIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getCustomerIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getCustomerIDAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setName1Request", ReplyAction="http://API.Integration/DataCustomerContact30/setName1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setName1Async(string UUID, string Name, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setExternalIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setExternalIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setExternalIDAsync(string UUID, string ExternalID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getExternalIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getExternalIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getExternalIDAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setPhoneRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setPhoneResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setPhoneAsync(string UUID, string PhoneNumber, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getName1Request", ReplyAction="http://API.Integration/DataCustomerContact30/getName1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getName1Async(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setName2Request", ReplyAction="http://API.Integration/DataCustomerContact30/setName2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setName2Async(string UUID, string Name, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/insert2Request", ReplyAction="http://API.Integration/DataCustomerContact30/insert2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> insert2Async(string UUID, Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactIN CustomerContactIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getName2Request", ReplyAction="http://API.Integration/DataCustomerContact30/getName2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getName2Async(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getEmailRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getEmailAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setCostCenterRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setCostCenterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setCostCenterAsync(string UUID, string CostCenter, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getUserIdRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getUserIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getUserIdAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getMobilePhoneRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getMobilePhoneResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getMobilePhoneAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getPhoneRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getPhoneResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getPhoneAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/seekByExternalIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/seekByExternalIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerArrayResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerArrayResult> seekByExternalIDAsync(string UUID, string ExternalID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setEmailRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setEmailAsync(string UUID, string EMail, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setFaxRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setFaxResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setFaxAsync(string UUID, string Fax, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getCostCenterRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getCostCenterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getCostCenterAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setMobilePhoneRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setMobilePhoneResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setMobilePhoneAsync(string UUID, string PhoneNumber, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getFaxRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getFaxResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getFaxAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getAddressIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getAddressIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getAddressIDAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getContactObjectRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getContactObjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CustomerContactResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactResult> getContactObjectAsync(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setSupervisor2Request", ReplyAction="http://API.Integration/DataCustomerContact30/setSupervisor2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setSupervisor2Async(string UUID, string LoginName, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getSupervisor2Request", ReplyAction="http://API.Integration/DataCustomerContact30/getSupervisor2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getSupervisor2Async(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getSupervisor1Request", ReplyAction="http://API.Integration/DataCustomerContact30/getSupervisor1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getSupervisor1Async(string UUID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setSupervisor1Request", ReplyAction="http://API.Integration/DataCustomerContact30/setSupervisor1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setSupervisor1Async(string UUID, string LoginName, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setCustomerIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setCustomerIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setCustomerIDAsync(string UUID, int CustomerID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/setAddressIDRequest", ReplyAction="http://API.Integration/DataCustomerContact30/setAddressIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setAddressIDAsync(string UUID, int AddressID, int ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomerContact30/getAllContactsRequest", ReplyAction="http://API.Integration/DataCustomerContact30/getAllContactsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerArrayResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerArrayResult> getAllContactsAsync(string UUID, int CustomerID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CustomerContactIN
    {
        
        private int addressIDField;
        
        private string costCenterField;
        
        private int customerContactIDField;
        
        private int customerIDField;
        
        private string emailField;
        
        private string externalIDField;
        
        private string faxField;
        
        private string mobilePhoneField;
        
        private string name1Field;
        
        private string name2Field;
        
        private string phoneField;
        
        private int statusField;
        
        private string supervisor1Field;
        
        private string supervisor2Field;
        
        private int userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int addressID
        {
            get
            {
                return this.addressIDField;
            }
            set
            {
                this.addressIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string costCenter
        {
            get
            {
                return this.costCenterField;
            }
            set
            {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int customerContactID
        {
            get
            {
                return this.customerContactIDField;
            }
            set
            {
                this.customerContactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int customerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string externalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string mobilePhone
        {
            get
            {
                return this.mobilePhoneField;
            }
            set
            {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string name1
        {
            get
            {
                return this.name1Field;
            }
            set
            {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string supervisor1
        {
            get
            {
                return this.supervisor1Field;
            }
            set
            {
                this.supervisor1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string supervisor2
        {
            get
            {
                return this.supervisor2Field;
            }
            set
            {
                this.supervisor2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CustomerContact
    {
        
        private int addressIDField;
        
        private string costCenterField;
        
        private int customerContactIDField;
        
        private int customerIDField;
        
        private string emailField;
        
        private string externalIDField;
        
        private string faxField;
        
        private string mobilePhoneField;
        
        private string name1Field;
        
        private string name2Field;
        
        private string phoneField;
        
        private int statusField;
        
        private string supervisor1Field;
        
        private string supervisor2Field;
        
        private int userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int addressID
        {
            get
            {
                return this.addressIDField;
            }
            set
            {
                this.addressIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string costCenter
        {
            get
            {
                return this.costCenterField;
            }
            set
            {
                this.costCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int customerContactID
        {
            get
            {
                return this.customerContactIDField;
            }
            set
            {
                this.customerContactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int customerID
        {
            get
            {
                return this.customerIDField;
            }
            set
            {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string externalID
        {
            get
            {
                return this.externalIDField;
            }
            set
            {
                this.externalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string mobilePhone
        {
            get
            {
                return this.mobilePhoneField;
            }
            set
            {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string name1
        {
            get
            {
                return this.name1Field;
            }
            set
            {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string supervisor1
        {
            get
            {
                return this.supervisor1Field;
            }
            set
            {
                this.supervisor1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string supervisor2
        {
            get
            {
                return this.supervisor2Field;
            }
            set
            {
                this.supervisor2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerArrayResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerContactResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerContactListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Result
    {
        
        private int statusCodeField;
        
        private string statusCodeAlphanumericField;
        
        private string statusMessageField;
        
        private System.Nullable<int>[] warning_StatusCodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCodeAlphanumeric
        {
            get
            {
                return this.statusCodeAlphanumericField;
            }
            set
            {
                this.statusCodeAlphanumericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("warning_StatusCodeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int>[] warning_StatusCodeList
        {
            get
            {
                return this.warning_StatusCodeListField;
            }
            set
            {
                this.warning_StatusCodeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class IntegerArrayResult : Result
    {
        
        private System.Nullable<int>[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int>[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CustomerContactResult : Result
    {
        
        private CustomerContact dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerContact data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class IntegerResult : Result
    {
        
        private int dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CustomerContactListResult : Result
    {
        
        private CustomerContact[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public CustomerContact[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringResult : Result
    {
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DataCustomerContact30Channel : Blackbird.Plugins.Plunet.DataCustomerContact30Service.DataCustomerContact30, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DataCustomerContact30Client : System.ServiceModel.ClientBase<Blackbird.Plugins.Plunet.DataCustomerContact30Service.DataCustomerContact30>, Blackbird.Plugins.Plunet.DataCustomerContact30Service.DataCustomerContact30
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataCustomerContact30Client() : 
                base(DataCustomerContact30Client.GetDefaultBinding(), DataCustomerContact30Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataCustomerContact30Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomerContact30Client(EndpointConfiguration endpointConfiguration) : 
                base(DataCustomerContact30Client.GetBindingForEndpoint(endpointConfiguration), DataCustomerContact30Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomerContact30Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataCustomerContact30Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomerContact30Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataCustomerContact30Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomerContact30Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> updateAsync(string UUID, Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactIN CustomerContactIN, bool enableNullOrEmptyValues)
        {
            return base.Channel.updateAsync(UUID, CustomerContactIN, enableNullOrEmptyValues);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> insertAsync(string UUID, int partnerID)
        {
            return base.Channel.insertAsync(UUID, partnerID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getStatusAsync(string UUID, int ContactID)
        {
            return base.Channel.getStatusAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setStatusAsync(string UUID, int Status, int ContactID)
        {
            return base.Channel.setStatusAsync(UUID, Status, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactListResult> getAllContactObjectsAsync(string UUID, int CustomerID)
        {
            return base.Channel.getAllContactObjectsAsync(UUID, CustomerID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getCustomerIDAsync(string UUID, int ContactID)
        {
            return base.Channel.getCustomerIDAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setName1Async(string UUID, string Name, int ContactID)
        {
            return base.Channel.setName1Async(UUID, Name, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setExternalIDAsync(string UUID, string ExternalID, int ContactID)
        {
            return base.Channel.setExternalIDAsync(UUID, ExternalID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getExternalIDAsync(string UUID, int ContactID)
        {
            return base.Channel.getExternalIDAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setPhoneAsync(string UUID, string PhoneNumber, int ContactID)
        {
            return base.Channel.setPhoneAsync(UUID, PhoneNumber, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getName1Async(string UUID, int ContactID)
        {
            return base.Channel.getName1Async(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setName2Async(string UUID, string Name, int ContactID)
        {
            return base.Channel.setName2Async(UUID, Name, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> insert2Async(string UUID, Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactIN CustomerContactIN)
        {
            return base.Channel.insert2Async(UUID, CustomerContactIN);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getName2Async(string UUID, int ContactID)
        {
            return base.Channel.getName2Async(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getEmailAsync(string UUID, int ContactID)
        {
            return base.Channel.getEmailAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setCostCenterAsync(string UUID, string CostCenter, int ContactID)
        {
            return base.Channel.setCostCenterAsync(UUID, CostCenter, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getUserIdAsync(string UUID, int ContactID)
        {
            return base.Channel.getUserIdAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getMobilePhoneAsync(string UUID, int ContactID)
        {
            return base.Channel.getMobilePhoneAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getPhoneAsync(string UUID, int ContactID)
        {
            return base.Channel.getPhoneAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerArrayResult> seekByExternalIDAsync(string UUID, string ExternalID)
        {
            return base.Channel.seekByExternalIDAsync(UUID, ExternalID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setEmailAsync(string UUID, string EMail, int ContactID)
        {
            return base.Channel.setEmailAsync(UUID, EMail, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setFaxAsync(string UUID, string Fax, int ContactID)
        {
            return base.Channel.setFaxAsync(UUID, Fax, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getCostCenterAsync(string UUID, int ContactID)
        {
            return base.Channel.getCostCenterAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setMobilePhoneAsync(string UUID, string PhoneNumber, int ContactID)
        {
            return base.Channel.setMobilePhoneAsync(UUID, PhoneNumber, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getFaxAsync(string UUID, int ContactID)
        {
            return base.Channel.getFaxAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerResult> getAddressIDAsync(string UUID, int ContactID)
        {
            return base.Channel.getAddressIDAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.CustomerContactResult> getContactObjectAsync(string UUID, int ContactID)
        {
            return base.Channel.getContactObjectAsync(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setSupervisor2Async(string UUID, string LoginName, int ContactID)
        {
            return base.Channel.setSupervisor2Async(UUID, LoginName, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getSupervisor2Async(string UUID, int ContactID)
        {
            return base.Channel.getSupervisor2Async(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.StringResult> getSupervisor1Async(string UUID, int ContactID)
        {
            return base.Channel.getSupervisor1Async(UUID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setSupervisor1Async(string UUID, string LoginName, int ContactID)
        {
            return base.Channel.setSupervisor1Async(UUID, LoginName, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setCustomerIDAsync(string UUID, int CustomerID, int ContactID)
        {
            return base.Channel.setCustomerIDAsync(UUID, CustomerID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.Result> setAddressIDAsync(string UUID, int AddressID, int ContactID)
        {
            return base.Channel.setAddressIDAsync(UUID, AddressID, ContactID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomerContact30Service.IntegerArrayResult> getAllContactsAsync(string UUID, int CustomerID)
        {
            return base.Channel.getAllContactsAsync(UUID, CustomerID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCustomerContact30Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCustomerContact30Port))
            {
                return new System.ServiceModel.EndpointAddress("https://test71.plunet.com/DataCustomerContact30");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataCustomerContact30Client.GetBindingForEndpoint(EndpointConfiguration.DataCustomerContact30Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataCustomerContact30Client.GetEndpointAddress(EndpointConfiguration.DataCustomerContact30Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DataCustomerContact30Port,
        }
    }
}
