//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbird.Plugins.Plunet.DataAdmin30Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://API.Integration/", ConfigurationName="Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30")]
    public interface DataAdmin30
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getPropertyValueListRequest", ReplyAction="http://API.Integration/DataAdmin30/getPropertyValueListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PropertyValueListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.PropertyValueListResult> getPropertyValueListAsync(string UUID, string PropertyNameEnglish, string LanguageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableWorkflowsRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableWorkflowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="WorkflowListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.WorkflowListResult> getAvailableWorkflowsAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableServicesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableServicesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServiceListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.ServiceListResult> getAvailableServicesAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableDocumentTemplatesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableDocumentTemplatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringArrayResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringArrayResult> getAvailableDocumentTemplatesAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableCountriesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableCountriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CountryListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CountryListResult> getAvailableCountriesAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getListOfRegisteredCallbacksRequest", ReplyAction="http://API.Integration/DataAdmin30/getListOfRegisteredCallbacksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CallbackListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CallbackListResult> getListOfRegisteredCallbacksAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getSystemCurrenciesRequest", ReplyAction="http://API.Integration/DataAdmin30/getSystemCurrenciesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CurrencyListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CurrencyList> getSystemCurrenciesAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableLanguagesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableLanguagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="LanguageListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.LanguageListResult> getAvailableLanguagesAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getDomesticCurrencyRequest", ReplyAction="http://API.Integration/DataAdmin30/getDomesticCurrencyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringResult> getDomesticCurrencyAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailablePriceUnitsRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailablePriceUnitsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PriceUnitListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.PriceUnitListResult> getAvailablePriceUnitsAsync(string UUID, string languageCode, string service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/seekLanguageByCatCodeRequest", ReplyAction="http://API.Integration/DataAdmin30/seekLanguageByCatCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="LanguageResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.languageResult> seekLanguageByCatCodeAsync(string UUID, string catCode, int catType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailablePropertiesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailablePropertiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PropertyListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.PropertyListResult> getAvailablePropertiesAsync(string UUID, int PropertyUsageArea, int MainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getAvailableTextModulesRequest", ReplyAction="http://API.Integration/DataAdmin30/getAvailableTextModulesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TextmoduleListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.TextmoduleListResult> getAvailableTextModulesAsync(string UUID, string languageCode, int textModuleUsageArea, int MainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getCompanyCodeListRequest", ReplyAction="http://API.Integration/DataAdmin30/getCompanyCodeListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompanyCodeListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CompanyCodeListResult> getCompanyCodeListAsync(string UUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataAdmin30/getLanguageCatCodeRequest", ReplyAction="http://API.Integration/DataAdmin30/getLanguageCatCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringResult> getLanguageCatCodeAsync(string UUID, string languageName, int catType);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PropertyValueListResult : Result
    {
        
        private PropertyValue[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public PropertyValue[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PropertyValue
    {
        
        private bool activeField;
        
        private int idField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Service
    {
        
        private string abbreviationField;
        
        private int idField;
        
        private string jobCategoryField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string jobCategory
        {
            get
            {
                return this.jobCategoryField;
            }
            set
            {
                this.jobCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CompanyCode
    {
        
        private int companyCodeIDField;
        
        private bool companyCodeRightsField;
        
        private string description_LongField;
        
        private string description_ShortField;
        
        private bool isCompanyCodeInvoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int companyCodeID
        {
            get
            {
                return this.companyCodeIDField;
            }
            set
            {
                this.companyCodeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool companyCodeRights
        {
            get
            {
                return this.companyCodeRightsField;
            }
            set
            {
                this.companyCodeRightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description_Long
        {
            get
            {
                return this.description_LongField;
            }
            set
            {
                this.description_LongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description_Short
        {
            get
            {
                return this.description_ShortField;
            }
            set
            {
                this.description_ShortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isCompanyCodeInvoice
        {
            get
            {
                return this.isCompanyCodeInvoiceField;
            }
            set
            {
                this.isCompanyCodeInvoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Callback
    {
        
        private int benutzerIDField;
        
        private int callbackTypeField;
        
        private int dataServiceField;
        
        private int errorCountField;
        
        private int eventTypeField;
        
        private int mainIDField;
        
        private int objectTypeField;
        
        private string serverAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int benutzerID
        {
            get
            {
                return this.benutzerIDField;
            }
            set
            {
                this.benutzerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int callbackType
        {
            get
            {
                return this.callbackTypeField;
            }
            set
            {
                this.callbackTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dataService
        {
            get
            {
                return this.dataServiceField;
            }
            set
            {
                this.dataServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int errorCount
        {
            get
            {
                return this.errorCountField;
            }
            set
            {
                this.errorCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int eventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int mainID
        {
            get
            {
                return this.mainIDField;
            }
            set
            {
                this.mainIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int objectType
        {
            get
            {
                return this.objectTypeField;
            }
            set
            {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string serverAddress
        {
            get
            {
                return this.serverAddressField;
            }
            set
            {
                this.serverAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Textmodule
    {
        
        private string[] availableValuesField;
        
        private System.DateTime dateValueField;
        
        private bool dateValueFieldSpecified;
        
        private string flagField;
        
        private string flag_MainTextModuleField;
        
        private string[] selectedValuesField;
        
        private string stringValueField;
        
        private string textModuleLabelField;
        
        private int textModuleTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availableValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] availableValues
        {
            get
            {
                return this.availableValuesField;
            }
            set
            {
                this.availableValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateValue
        {
            get
            {
                return this.dateValueField;
            }
            set
            {
                this.dateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateValueSpecified
        {
            get
            {
                return this.dateValueFieldSpecified;
            }
            set
            {
                this.dateValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string flag_MainTextModule
        {
            get
            {
                return this.flag_MainTextModuleField;
            }
            set
            {
                this.flag_MainTextModuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] selectedValues
        {
            get
            {
                return this.selectedValuesField;
            }
            set
            {
                this.selectedValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string stringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string textModuleLabel
        {
            get
            {
                return this.textModuleLabelField;
            }
            set
            {
                this.textModuleLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int textModuleType
        {
            get
            {
                return this.textModuleTypeField;
            }
            set
            {
                this.textModuleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceUnit
    {
        
        private bool activeField;
        
        private string articleNumberField;
        
        private string descriptionField;
        
        private string memoField;
        
        private int priceUnitIDField;
        
        private string serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string articleNumber
        {
            get
            {
                return this.articleNumberField;
            }
            set
            {
                this.articleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int priceUnitID
        {
            get
            {
                return this.priceUnitIDField;
            }
            set
            {
                this.priceUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Country
    {
        
        private int idField;
        
        private string isoCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isoCode
        {
            get
            {
                return this.isoCodeField;
            }
            set
            {
                this.isoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Workflow
    {
        
        private string descriptionField;
        
        private string nameField;
        
        private int statusField;
        
        private int typeField;
        
        private int workflowIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int workflowId
        {
            get
            {
                return this.workflowIdField;
            }
            set
            {
                this.workflowIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Language
    {
        
        private bool activeField;
        
        private bool favoriteField;
        
        private string folderNameField;
        
        private int idField;
        
        private string isoCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool favorite
        {
            get
            {
                return this.favoriteField;
            }
            set
            {
                this.favoriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string folderName
        {
            get
            {
                return this.folderNameField;
            }
            set
            {
                this.folderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isoCode
        {
            get
            {
                return this.isoCodeField;
            }
            set
            {
                this.isoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Currency
    {
        
        private int currencyIDField;
        
        private string descriptionField;
        
        private string isoCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int currencyID
        {
            get
            {
                return this.currencyIDField;
            }
            set
            {
                this.currencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string isoCode
        {
            get
            {
                return this.isoCodeField;
            }
            set
            {
                this.isoCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Property
    {
        
        private System.Nullable<int>[] avaliablePropertyValueIDListField;
        
        private string mainPropertyNameEnglishField;
        
        private string propertyNameEnglishField;
        
        private int propertyTypeField;
        
        private int selectedPropertyValueIDField;
        
        private System.Nullable<int>[] selectedPropertyValueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avaliablePropertyValueIDList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int>[] avaliablePropertyValueIDList
        {
            get
            {
                return this.avaliablePropertyValueIDListField;
            }
            set
            {
                this.avaliablePropertyValueIDListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mainPropertyNameEnglish
        {
            get
            {
                return this.mainPropertyNameEnglishField;
            }
            set
            {
                this.mainPropertyNameEnglishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string propertyNameEnglish
        {
            get
            {
                return this.propertyNameEnglishField;
            }
            set
            {
                this.propertyNameEnglishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int propertyType
        {
            get
            {
                return this.propertyTypeField;
            }
            set
            {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int selectedPropertyValueID
        {
            get
            {
                return this.selectedPropertyValueIDField;
            }
            set
            {
                this.selectedPropertyValueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedPropertyValueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int>[] selectedPropertyValueList
        {
            get
            {
                return this.selectedPropertyValueListField;
            }
            set
            {
                this.selectedPropertyValueListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringArrayResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CompanyCodeListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CallbackListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextmoduleListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceUnitListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CountryListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkflowListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyValueListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(languageResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LanguageListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurrencyList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyListResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Result
    {
        
        private int statusCodeField;
        
        private string statusCodeAlphanumericField;
        
        private string statusMessageField;
        
        private System.Nullable<int>[] warning_StatusCodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCodeAlphanumeric
        {
            get
            {
                return this.statusCodeAlphanumericField;
            }
            set
            {
                this.statusCodeAlphanumericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("warning_StatusCodeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int>[] warning_StatusCodeList
        {
            get
            {
                return this.warning_StatusCodeListField;
            }
            set
            {
                this.warning_StatusCodeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringArrayResult : Result
    {
        
        private string[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class ServiceListResult : Result
    {
        
        private Service[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Service[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CompanyCodeListResult : Result
    {
        
        private CompanyCode[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public CompanyCode[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CallbackListResult : Result
    {
        
        private Callback[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Callback[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class TextmoduleListResult : Result
    {
        
        private Textmodule[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Textmodule[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringResult : Result
    {
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceUnitListResult : Result
    {
        
        private PriceUnit[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public PriceUnit[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CountryListResult : Result
    {
        
        private Country[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Country[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class WorkflowListResult : Result
    {
        
        private Workflow[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Workflow[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class languageResult : Result
    {
        
        private Language dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Language data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class LanguageListResult : Result
    {
        
        private Language[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Language[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class CurrencyList : Result
    {
        
        private Currency[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Currency[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PropertyResult : Result
    {
        
        private Property dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Property data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PropertyListResult : Result
    {
        
        private PropertyResult[] m_DataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("m_Data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public PropertyResult[] m_Data
        {
            get
            {
                return this.m_DataField;
            }
            set
            {
                this.m_DataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface DataAdmin30Channel : Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DataAdmin30Client : System.ServiceModel.ClientBase<Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30>, Blackbird.Plugins.Plunet.DataAdmin30Service.DataAdmin30
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataAdmin30Client() : 
                base(DataAdmin30Client.GetDefaultBinding(), DataAdmin30Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataAdmin30Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(EndpointConfiguration endpointConfiguration) : 
                base(DataAdmin30Client.GetBindingForEndpoint(endpointConfiguration), DataAdmin30Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataAdmin30Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataAdmin30Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataAdmin30Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.PropertyValueListResult> getPropertyValueListAsync(string UUID, string PropertyNameEnglish, string LanguageCode)
        {
            return base.Channel.getPropertyValueListAsync(UUID, PropertyNameEnglish, LanguageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.WorkflowListResult> getAvailableWorkflowsAsync(string UUID)
        {
            return base.Channel.getAvailableWorkflowsAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.ServiceListResult> getAvailableServicesAsync(string UUID, string languageCode)
        {
            return base.Channel.getAvailableServicesAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringArrayResult> getAvailableDocumentTemplatesAsync(string UUID)
        {
            return base.Channel.getAvailableDocumentTemplatesAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CountryListResult> getAvailableCountriesAsync(string UUID, string languageCode)
        {
            return base.Channel.getAvailableCountriesAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CallbackListResult> getListOfRegisteredCallbacksAsync(string UUID)
        {
            return base.Channel.getListOfRegisteredCallbacksAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CurrencyList> getSystemCurrenciesAsync(string UUID)
        {
            return base.Channel.getSystemCurrenciesAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.LanguageListResult> getAvailableLanguagesAsync(string UUID, string languageCode)
        {
            return base.Channel.getAvailableLanguagesAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringResult> getDomesticCurrencyAsync(string UUID)
        {
            return base.Channel.getDomesticCurrencyAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.PriceUnitListResult> getAvailablePriceUnitsAsync(string UUID, string languageCode, string service)
        {
            return base.Channel.getAvailablePriceUnitsAsync(UUID, languageCode, service);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.languageResult> seekLanguageByCatCodeAsync(string UUID, string catCode, int catType)
        {
            return base.Channel.seekLanguageByCatCodeAsync(UUID, catCode, catType);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.PropertyListResult> getAvailablePropertiesAsync(string UUID, int PropertyUsageArea, int MainID)
        {
            return base.Channel.getAvailablePropertiesAsync(UUID, PropertyUsageArea, MainID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.TextmoduleListResult> getAvailableTextModulesAsync(string UUID, string languageCode, int textModuleUsageArea, int MainID)
        {
            return base.Channel.getAvailableTextModulesAsync(UUID, languageCode, textModuleUsageArea, MainID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.CompanyCodeListResult> getCompanyCodeListAsync(string UUID)
        {
            return base.Channel.getCompanyCodeListAsync(UUID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataAdmin30Service.StringResult> getLanguageCatCodeAsync(string UUID, string languageName, int catType)
        {
            return base.Channel.getLanguageCatCodeAsync(UUID, languageName, catType);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataAdmin30Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataAdmin30Port))
            {
                return new System.ServiceModel.EndpointAddress("https://plunet-friend-blackbird.plunet.com/DataAdmin30");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataAdmin30Client.GetBindingForEndpoint(EndpointConfiguration.DataAdmin30Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataAdmin30Client.GetEndpointAddress(EndpointConfiguration.DataAdmin30Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DataAdmin30Port,
        }
    }
}
