//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbird.Plugins.Plunet.DataCustomFields30
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://API.Integration/", ConfigurationName="Blackbird.Plugins.Plunet.DataCustomFields30.DataCustomFields30")]
    public interface DataCustomFields30
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomFields30/getPropertyRequest", ReplyAction="http://API.Integration/DataCustomFields30/getPropertyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PropertyResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.PropertyResult> getPropertyAsync(string UUID, string PropertyNameEnglish, int PropertyUsageArea, int MainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomFields30/setPropertyValueRequest", ReplyAction="http://API.Integration/DataCustomFields30/setPropertyValueResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.Result> setPropertyValueAsync(string UUID, string PropertyNameEnglish, int PropertyUsageArea, int PropertyValueID, int MainID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomFields30/setPropertyValueListRequest", ReplyAction="http://API.Integration/DataCustomFields30/setPropertyValueListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListResponse> setPropertyValueListAsync(Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomFields30/getPropertyValueTextRequest", ReplyAction="http://API.Integration/DataCustomFields30/getPropertyValueTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.StringResult> getPropertyValueTextAsync(string UUID, string PropertyNameEnglish, int PropertyValueID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomFields30/setTextmoduleRequest", ReplyAction="http://API.Integration/DataCustomFields30/setTextmoduleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TextmoduleResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.Result> setTextmoduleAsync(string UUID, Blackbird.Plugins.Plunet.DataCustomFields30.TextmoduleIN TextmoduleIN, int ID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataCustomFields30/getTextmoduleRequest", ReplyAction="http://API.Integration/DataCustomFields30/getTextmoduleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TextmoduleResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.TextmoduleResult> getTextmoduleAsync(string UUID, string Flag, int TextModuleUsageArea, int ID, string languageCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PropertyResult : Result
    {
        
        private Property dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Property data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Property
    {
        
        private System.Nullable<int>[] avaliablePropertyValueIDListField;
        
        private string mainPropertyNameEnglishField;
        
        private string propertyNameEnglishField;
        
        private int propertyTypeField;
        
        private int selectedPropertyValueIDField;
        
        private System.Nullable<int>[] selectedPropertyValueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avaliablePropertyValueIDList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int>[] avaliablePropertyValueIDList
        {
            get
            {
                return this.avaliablePropertyValueIDListField;
            }
            set
            {
                this.avaliablePropertyValueIDListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mainPropertyNameEnglish
        {
            get
            {
                return this.mainPropertyNameEnglishField;
            }
            set
            {
                this.mainPropertyNameEnglishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string propertyNameEnglish
        {
            get
            {
                return this.propertyNameEnglishField;
            }
            set
            {
                this.propertyNameEnglishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int propertyType
        {
            get
            {
                return this.propertyTypeField;
            }
            set
            {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int selectedPropertyValueID
        {
            get
            {
                return this.selectedPropertyValueIDField;
            }
            set
            {
                this.selectedPropertyValueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedPropertyValueList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int>[] selectedPropertyValueList
        {
            get
            {
                return this.selectedPropertyValueListField;
            }
            set
            {
                this.selectedPropertyValueListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class TextmoduleIN
    {
        
        private System.DateTime dateValueField;
        
        private bool dateValueFieldSpecified;
        
        private string flagField;
        
        private string[] selectedValuesField;
        
        private string stringValueField;
        
        private int textModuleUsageAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dateValue
        {
            get
            {
                return this.dateValueField;
            }
            set
            {
                this.dateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateValueSpecified
        {
            get
            {
                return this.dateValueFieldSpecified;
            }
            set
            {
                this.dateValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] selectedValues
        {
            get
            {
                return this.selectedValuesField;
            }
            set
            {
                this.selectedValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string stringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int textModuleUsageArea
        {
            get
            {
                return this.textModuleUsageAreaField;
            }
            set
            {
                this.textModuleUsageAreaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Textmodule
    {
        
        private string[] availableValuesField;
        
        private System.DateTime dateValueField;
        
        private bool dateValueFieldSpecified;
        
        private string flagField;
        
        private string flag_MainTextModuleField;
        
        private string[] selectedValuesField;
        
        private string stringValueField;
        
        private string textModuleLabelField;
        
        private int textModuleTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availableValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] availableValues
        {
            get
            {
                return this.availableValuesField;
            }
            set
            {
                this.availableValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateValue
        {
            get
            {
                return this.dateValueField;
            }
            set
            {
                this.dateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateValueSpecified
        {
            get
            {
                return this.dateValueFieldSpecified;
            }
            set
            {
                this.dateValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string flag_MainTextModule
        {
            get
            {
                return this.flag_MainTextModuleField;
            }
            set
            {
                this.flag_MainTextModuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] selectedValues
        {
            get
            {
                return this.selectedValuesField;
            }
            set
            {
                this.selectedValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string stringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string textModuleLabel
        {
            get
            {
                return this.textModuleLabelField;
            }
            set
            {
                this.textModuleLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int textModuleType
        {
            get
            {
                return this.textModuleTypeField;
            }
            set
            {
                this.textModuleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextmoduleResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Result
    {
        
        private int statusCodeField;
        
        private string statusCodeAlphanumericField;
        
        private string statusMessageField;
        
        private System.Nullable<int>[] warning_StatusCodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCodeAlphanumeric
        {
            get
            {
                return this.statusCodeAlphanumericField;
            }
            set
            {
                this.statusCodeAlphanumericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("warning_StatusCodeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int>[] warning_StatusCodeList
        {
            get
            {
                return this.warning_StatusCodeListField;
            }
            set
            {
                this.warning_StatusCodeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringResult : Result
    {
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class TextmoduleResult : Result
    {
        
        private Textmodule dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Textmodule data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPropertyValueList", WrapperNamespace="http://API.Integration/", IsWrapped=true)]
    public partial class setPropertyValueListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string PropertyNameEnglish;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int PropertyUsageArea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("integerList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] PropertyValueList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int MainID;
        
        public setPropertyValueListRequest()
        {
        }
        
        public setPropertyValueListRequest(string UUID, string PropertyNameEnglish, int PropertyUsageArea, System.Nullable<int>[] PropertyValueList, int MainID)
        {
            this.UUID = UUID;
            this.PropertyNameEnglish = PropertyNameEnglish;
            this.PropertyUsageArea = PropertyUsageArea;
            this.PropertyValueList = PropertyValueList;
            this.MainID = MainID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPropertyValueListResponse", WrapperNamespace="http://API.Integration/", IsWrapped=true)]
    public partial class setPropertyValueListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Blackbird.Plugins.Plunet.DataCustomFields30.Result Result;
        
        public setPropertyValueListResponse()
        {
        }
        
        public setPropertyValueListResponse(Blackbird.Plugins.Plunet.DataCustomFields30.Result Result)
        {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface DataCustomFields30Channel : Blackbird.Plugins.Plunet.DataCustomFields30.DataCustomFields30, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DataCustomFields30Client : System.ServiceModel.ClientBase<Blackbird.Plugins.Plunet.DataCustomFields30.DataCustomFields30>, Blackbird.Plugins.Plunet.DataCustomFields30.DataCustomFields30
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataCustomFields30Client() : 
                base(DataCustomFields30Client.GetDefaultBinding(), DataCustomFields30Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataCustomFields30Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomFields30Client(EndpointConfiguration endpointConfiguration) : 
                base(DataCustomFields30Client.GetBindingForEndpoint(endpointConfiguration), DataCustomFields30Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomFields30Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataCustomFields30Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomFields30Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataCustomFields30Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCustomFields30Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.PropertyResult> getPropertyAsync(string UUID, string PropertyNameEnglish, int PropertyUsageArea, int MainID)
        {
            return base.Channel.getPropertyAsync(UUID, PropertyNameEnglish, PropertyUsageArea, MainID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.Result> setPropertyValueAsync(string UUID, string PropertyNameEnglish, int PropertyUsageArea, int PropertyValueID, int MainID)
        {
            return base.Channel.setPropertyValueAsync(UUID, PropertyNameEnglish, PropertyUsageArea, PropertyValueID, MainID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListResponse> Blackbird.Plugins.Plunet.DataCustomFields30.DataCustomFields30.setPropertyValueListAsync(Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListRequest request)
        {
            return base.Channel.setPropertyValueListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListResponse> setPropertyValueListAsync(string UUID, string PropertyNameEnglish, int PropertyUsageArea, System.Nullable<int>[] PropertyValueList, int MainID)
        {
            Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListRequest inValue = new Blackbird.Plugins.Plunet.DataCustomFields30.setPropertyValueListRequest();
            inValue.UUID = UUID;
            inValue.PropertyNameEnglish = PropertyNameEnglish;
            inValue.PropertyUsageArea = PropertyUsageArea;
            inValue.PropertyValueList = PropertyValueList;
            inValue.MainID = MainID;
            return ((Blackbird.Plugins.Plunet.DataCustomFields30.DataCustomFields30)(this)).setPropertyValueListAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.StringResult> getPropertyValueTextAsync(string UUID, string PropertyNameEnglish, int PropertyValueID, string languageCode)
        {
            return base.Channel.getPropertyValueTextAsync(UUID, PropertyNameEnglish, PropertyValueID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.Result> setTextmoduleAsync(string UUID, Blackbird.Plugins.Plunet.DataCustomFields30.TextmoduleIN TextmoduleIN, int ID, string languageCode)
        {
            return base.Channel.setTextmoduleAsync(UUID, TextmoduleIN, ID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataCustomFields30.TextmoduleResult> getTextmoduleAsync(string UUID, string Flag, int TextModuleUsageArea, int ID, string languageCode)
        {
            return base.Channel.getTextmoduleAsync(UUID, Flag, TextModuleUsageArea, ID, languageCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCustomFields30Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCustomFields30Port))
            {
                return new System.ServiceModel.EndpointAddress("https://plunet-friend-blackbird.plunet.com/DataCustomFields30");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataCustomFields30Client.GetBindingForEndpoint(EndpointConfiguration.DataCustomFields30Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataCustomFields30Client.GetEndpointAddress(EndpointConfiguration.DataCustomFields30Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DataCustomFields30Port,
        }
    }
}
