//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackbird.Plugins.Plunet.DataPayable30Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://API.Integration/", ConfigurationName="Blackbird.Plugins.Plunet.DataPayable30Service.DataPayable30")]
    public interface DataPayable30
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/searchRequest", ReplyAction="http://API.Integration/DataPayable30/searchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerArrayResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerArrayResult> searchAsync(string UUID, Blackbird.Plugins.Plunet.DataPayable30Service.SearchFilter_Payable SearchFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getCurrencyRequest", ReplyAction="http://API.Integration/DataPayable30/getCurrencyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getCurrencyAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setStatusRequest", ReplyAction="http://API.Integration/DataPayable30/setStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setStatusAsync(string UUID, int Status, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getStatusRequest", ReplyAction="http://API.Integration/DataPayable30/getStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getStatusAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPriceUnit_ListRequest", ReplyAction="http://API.Integration/DataPayable30/getPriceUnit_ListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PriceUnitListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceUnitListResult> getPriceUnit_ListAsync(string UUID, string languageCode, string service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPriceLine_ListRequest", ReplyAction="http://API.Integration/DataPayable30/getPriceLine_ListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PriceLineListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineListResult> getPriceLine_ListAsync(string UUID, int payablesItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getResourceIDRequest", ReplyAction="http://API.Integration/DataPayable30/getResourceIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getResourceIDAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/deletePriceLineRequest", ReplyAction="http://API.Integration/DataPayable30/deletePriceLineResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> deletePriceLineAsync(string UUID, int payablesItemID, int priceLineID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/updatePriceLineRequest", ReplyAction="http://API.Integration/DataPayable30/updatePriceLineResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PriceLineResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineResult> updatePriceLineAsync(string UUID, int payablesItemID, Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineIN priceLineIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPriceUnitRequest", ReplyAction="http://API.Integration/DataPayable30/getPriceUnitResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PriceUnitResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceUnitResult> getPriceUnitAsync(string UUID, int PriceUnitID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getServices_ListRequest", ReplyAction="http://API.Integration/DataPayable30/getServices_ListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringArrayResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringArrayResult> getServices_ListAsync(string UUID, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/insertPriceLineRequest", ReplyAction="http://API.Integration/DataPayable30/insertPriceLineResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PriceLineResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineResult> insertPriceLineAsync(string UUID, int payablesItemID, Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineIN priceLineIN, bool createAsFirstItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPayableIDRequest", ReplyAction="http://API.Integration/DataPayable30/getPayableIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getPayableIDAsync(string UUID, int itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getValueDateRequest", ReplyAction="http://API.Integration/DataPayable30/getValueDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DateResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getValueDateAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setValueDateRequest", ReplyAction="http://API.Integration/DataPayable30/setValueDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setValueDateAsync(string UUID, System.DateTime valueDate, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getInvoiceDateRequest", ReplyAction="http://API.Integration/DataPayable30/getInvoiceDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DateResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getInvoiceDateAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setInvoiceDateRequest", ReplyAction="http://API.Integration/DataPayable30/setInvoiceDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setInvoiceDateAsync(string UUID, System.DateTime invoiceDate, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getMemoRequest", ReplyAction="http://API.Integration/DataPayable30/getMemoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getMemoAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setMemoRequest", ReplyAction="http://API.Integration/DataPayable30/setMemoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setMemoAsync(string UUID, int payablesID, string memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPaidDateRequest", ReplyAction="http://API.Integration/DataPayable30/getPaidDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getPaidDateAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setPaidDateRequest", ReplyAction="http://API.Integration/DataPayable30/setPaidDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setPaidDateAsync(string UUID, int payablesID, System.DateTime paidDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getIsExportedRequest", ReplyAction="http://API.Integration/DataPayable30/getIsExportedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.BooleanResult> getIsExportedAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getCompanyCodeRequest", ReplyAction="http://API.Integration/DataPayable30/getCompanyCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getCompanyCodeAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setIsExportedRequest", ReplyAction="http://API.Integration/DataPayable30/setIsExportedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setIsExportedAsync(string UUID, int payablesID, bool isExported);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPaymentMethodRequest", ReplyAction="http://API.Integration/DataPayable30/getPaymentMethodResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IntegerResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getPaymentMethodAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setCreditorAccountRequest", ReplyAction="http://API.Integration/DataPayable30/setCreditorAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setCreditorAccountAsync(string UUID, string accountID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getTotalNetAmountRequest", ReplyAction="http://API.Integration/DataPayable30/getTotalNetAmountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DoubleResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DoubleResult> getTotalNetAmountAsync(string UUID, int payablesID, int currencyTpe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPaymentCreatorResourceIDRequest", ReplyAction="http://API.Integration/DataPayable30/getPaymentCreatorResourceIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getPaymentCreatorResourceIDAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setPaymentDueDateRequest", ReplyAction="http://API.Integration/DataPayable30/setPaymentDueDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setPaymentDueDateAsync(string UUID, int payablesID, System.DateTime dueDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getExternalInvoiceNumberRequest", ReplyAction="http://API.Integration/DataPayable30/getExternalInvoiceNumberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getExternalInvoiceNumberAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setExternalInvoiceNumberRequest", ReplyAction="http://API.Integration/DataPayable30/setExternalInvoiceNumberResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setExternalInvoiceNumberAsync(string UUID, int payablesID, string externalNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getAccountStatementRequest", ReplyAction="http://API.Integration/DataPayable30/getAccountStatementResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getAccountStatementAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getInvoiceTaxTypesRequest", ReplyAction="http://API.Integration/DataPayable30/getInvoiceTaxTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TaxListResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.TaxListResult> getInvoiceTaxTypesAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getCreditorAccountRequest", ReplyAction="http://API.Integration/DataPayable30/getCreditorAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getCreditorAccountAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getTotalTaxAmountRequest", ReplyAction="http://API.Integration/DataPayable30/getTotalTaxAmountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DoubleResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DoubleResult> getTotalTaxAmountAsync(string UUID, int payablesID, int currencyTpe, int taxType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPaymentDueDateRequest", ReplyAction="http://API.Integration/DataPayable30/getPaymentDueDateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getPaymentDueDateAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/setAccountStatementRequest", ReplyAction="http://API.Integration/DataPayable30/setAccountStatementResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setAccountStatementAsync(string UUID, int payablesID, string accountstatement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getExpenseAccountRequest", ReplyAction="http://API.Integration/DataPayable30/getExpenseAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StringResult")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getExpenseAccountAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/insertPaymentItemRequest", ReplyAction="http://API.Integration/DataPayable30/insertPaymentItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> insertPaymentItemAsync(string UUID, Blackbird.Plugins.Plunet.DataPayable30Service.PayableItemIN PaymentItemIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/getPaymentItemListRequest", ReplyAction="http://API.Integration/DataPayable30/getPaymentItemListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PaymentItemResultList")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PayableItemResultList> getPaymentItemListAsync(string UUID, int payablesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/deletePaymentItemRequest", ReplyAction="http://API.Integration/DataPayable30/deletePaymentItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> deletePaymentItemAsync(string UUID, int PaymentItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://API.Integration/DataPayable30/updatePaymentItemRequest", ReplyAction="http://API.Integration/DataPayable30/updatePaymentItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> updatePaymentItemAsync(string UUID, Blackbird.Plugins.Plunet.DataPayable30Service.PayableItemIN PaymentItemIN, int PaymentItemID, bool enableNullOrEmptyValues);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class SearchFilter_Payable
    {
        
        private int exportedField;
        
        private string isoCodeCurrencyField;
        
        private string languageCodeField;
        
        private int resourceIDField;
        
        private int payableStatusField;
        
        private Textmodule[] textmodulesListField;
        
        private SelectionEntry_TimeFrame timeFrameField;
        
        public SearchFilter_Payable()
        {
            this.exportedField = 3;
            this.languageCodeField = "EN";
            this.resourceIDField = -1;
            this.payableStatusField = -1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int exported
        {
            get
            {
                return this.exportedField;
            }
            set
            {
                this.exportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isoCodeCurrency
        {
            get
            {
                return this.isoCodeCurrencyField;
            }
            set
            {
                this.isoCodeCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.ComponentModel.DefaultValueAttribute("EN")]
        public string languageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int resourceID
        {
            get
            {
                return this.resourceIDField;
            }
            set
            {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int payableStatus
        {
            get
            {
                return this.payableStatusField;
            }
            set
            {
                this.payableStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("textmodulesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Textmodule[] textmodulesList
        {
            get
            {
                return this.textmodulesListField;
            }
            set
            {
                this.textmodulesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public SelectionEntry_TimeFrame timeFrame
        {
            get
            {
                return this.timeFrameField;
            }
            set
            {
                this.timeFrameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Textmodule
    {
        
        private string[] availableValuesField;
        
        private System.DateTime dateValueField;
        
        private bool dateValueFieldSpecified;
        
        private string flagField;
        
        private string flag_MainTextModuleField;
        
        private string[] selectedValuesField;
        
        private string stringValueField;
        
        private string textModuleLabelField;
        
        private int textModuleTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availableValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] availableValues
        {
            get
            {
                return this.availableValuesField;
            }
            set
            {
                this.availableValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateValue
        {
            get
            {
                return this.dateValueField;
            }
            set
            {
                this.dateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateValueSpecified
        {
            get
            {
                return this.dateValueFieldSpecified;
            }
            set
            {
                this.dateValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string flag_MainTextModule
        {
            get
            {
                return this.flag_MainTextModuleField;
            }
            set
            {
                this.flag_MainTextModuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectedValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] selectedValues
        {
            get
            {
                return this.selectedValuesField;
            }
            set
            {
                this.selectedValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string stringValue
        {
            get
            {
                return this.stringValueField;
            }
            set
            {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string textModuleLabel
        {
            get
            {
                return this.textModuleLabelField;
            }
            set
            {
                this.textModuleLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int textModuleType
        {
            get
            {
                return this.textModuleTypeField;
            }
            set
            {
                this.textModuleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PayableItemIN
    {
        
        private string briefDescriptionField;
        
        private int invoiceIDField;
        
        private int itemNumberField;
        
        private System.DateTime jobDateField;
        
        private bool jobDateFieldSpecified;
        
        private int jobIDField;
        
        private string jobNoField;
        
        private int jobStatusField;
        
        private double totalpriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string briefDescription
        {
            get
            {
                return this.briefDescriptionField;
            }
            set
            {
                this.briefDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int invoiceID
        {
            get
            {
                return this.invoiceIDField;
            }
            set
            {
                this.invoiceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int itemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime jobDate
        {
            get
            {
                return this.jobDateField;
            }
            set
            {
                this.jobDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jobDateSpecified
        {
            get
            {
                return this.jobDateFieldSpecified;
            }
            set
            {
                this.jobDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int jobID
        {
            get
            {
                return this.jobIDField;
            }
            set
            {
                this.jobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string jobNo
        {
            get
            {
                return this.jobNoField;
            }
            set
            {
                this.jobNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int jobStatus
        {
            get
            {
                return this.jobStatusField;
            }
            set
            {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double totalprice
        {
            get
            {
                return this.totalpriceField;
            }
            set
            {
                this.totalpriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceLineIN
    {
        
        private double amountField;
        
        private double amount_perUnitField;
        
        private string memoField;
        
        private int priceLineIDField;
        
        private int priceUnitIDField;
        
        private int taxTypeField;
        
        private double time_perUnitField;
        
        private double unit_priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double amount_perUnit
        {
            get
            {
                return this.amount_perUnitField;
            }
            set
            {
                this.amount_perUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int priceLineID
        {
            get
            {
                return this.priceLineIDField;
            }
            set
            {
                this.priceLineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int priceUnitID
        {
            get
            {
                return this.priceUnitIDField;
            }
            set
            {
                this.priceUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int taxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double time_perUnit
        {
            get
            {
                return this.time_perUnitField;
            }
            set
            {
                this.time_perUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double unit_price
        {
            get
            {
                return this.unit_priceField;
            }
            set
            {
                this.unit_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PayableItem
    {
        
        private string briefDescriptionField;
        
        private int invoiceIDField;
        
        private int itemNumberField;
        
        private System.DateTime jobDateField;
        
        private bool jobDateFieldSpecified;
        
        private string jobNoField;
        
        private int jobStatusField;
        
        private int payableItemIDField;
        
        private int projectTypeField;
        
        private double totalpriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string briefDescription
        {
            get
            {
                return this.briefDescriptionField;
            }
            set
            {
                this.briefDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int invoiceID
        {
            get
            {
                return this.invoiceIDField;
            }
            set
            {
                this.invoiceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int itemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime jobDate
        {
            get
            {
                return this.jobDateField;
            }
            set
            {
                this.jobDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jobDateSpecified
        {
            get
            {
                return this.jobDateFieldSpecified;
            }
            set
            {
                this.jobDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string jobNo
        {
            get
            {
                return this.jobNoField;
            }
            set
            {
                this.jobNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int jobStatus
        {
            get
            {
                return this.jobStatusField;
            }
            set
            {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int payableItemID
        {
            get
            {
                return this.payableItemIDField;
            }
            set
            {
                this.payableItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int projectType
        {
            get
            {
                return this.projectTypeField;
            }
            set
            {
                this.projectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double totalprice
        {
            get
            {
                return this.totalpriceField;
            }
            set
            {
                this.totalpriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceUnit
    {
        
        private string articleNumberField;
        
        private string descriptionField;
        
        private string memoField;
        
        private int priceUnitIDField;
        
        private string serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string articleNumber
        {
            get
            {
                return this.articleNumberField;
            }
            set
            {
                this.articleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int priceUnitID
        {
            get
            {
                return this.priceUnitIDField;
            }
            set
            {
                this.priceUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceLine
    {
        
        private double amountField;
        
        private double amount_perUnitField;
        
        private string memoField;
        
        private int priceLineIDField;
        
        private int priceUnitIDField;
        
        private int sequenceField;
        
        private int taxTypeField;
        
        private double time_perUnitField;
        
        private double unit_priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double amount_perUnit
        {
            get
            {
                return this.amount_perUnitField;
            }
            set
            {
                this.amount_perUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int priceLineID
        {
            get
            {
                return this.priceLineIDField;
            }
            set
            {
                this.priceLineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int priceUnitID
        {
            get
            {
                return this.priceUnitIDField;
            }
            set
            {
                this.priceUnitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int taxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double time_perUnit
        {
            get
            {
                return this.time_perUnitField;
            }
            set
            {
                this.time_perUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double unit_price
        {
            get
            {
                return this.unit_priceField;
            }
            set
            {
                this.unit_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Tax
    {
        
        private bool activeField;
        
        private string expenseAccountField;
        
        private string revenueAccountField;
        
        private string taxDescriptionField;
        
        private double taxRateField;
        
        private int taxTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string expenseAccount
        {
            get
            {
                return this.expenseAccountField;
            }
            set
            {
                this.expenseAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string revenueAccount
        {
            get
            {
                return this.revenueAccountField;
            }
            set
            {
                this.revenueAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string taxDescription
        {
            get
            {
                return this.taxDescriptionField;
            }
            set
            {
                this.taxDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double taxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int taxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringArrayResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerArrayResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceUnitResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PayableItemResultList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceLineListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceUnitListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceLineResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxListResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class Result
    {
        
        private int statusCodeField;
        
        private string statusCodeAlphanumericField;
        
        private string statusMessageField;
        
        private System.Nullable<int>[] warning_StatusCodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCodeAlphanumeric
        {
            get
            {
                return this.statusCodeAlphanumericField;
            }
            set
            {
                this.statusCodeAlphanumericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("warning_StatusCodeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int>[] warning_StatusCodeList
        {
            get
            {
                return this.warning_StatusCodeListField;
            }
            set
            {
                this.warning_StatusCodeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringArrayResult : Result
    {
        
        private string[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class IntegerArrayResult : Result
    {
        
        private System.Nullable<int>[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int>[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceUnitResult : Result
    {
        
        private PriceUnit dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PriceUnit data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PayableItemResultList : Result
    {
        
        private PayableItem[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public PayableItem[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceLineListResult : Result
    {
        
        private PriceLine[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public PriceLine[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class BooleanResult : Result
    {
        
        private bool dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceUnitListResult : Result
    {
        
        private PriceUnit[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public PriceUnit[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class PriceLineResult : Result
    {
        
        private PriceLine dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PriceLine data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class DateResult : Result
    {
        
        private System.DateTime dataField;
        
        private bool dataFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSpecified
        {
            get
            {
                return this.dataFieldSpecified;
            }
            set
            {
                this.dataFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class DoubleResult : Result
    {
        
        private double dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class TaxListResult : Result
    {
        
        private Tax[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Tax[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class IntegerResult : Result
    {
        
        private int dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class StringResult : Result
    {
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://API.Integration/")]
    public partial class SelectionEntry_TimeFrame
    {
        
        private System.DateTime dateFromField;
        
        private int dateRelationField;
        
        private System.DateTime dateToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int dateRelation
        {
            get
            {
                return this.dateRelationField;
            }
            set
            {
                this.dateRelationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime dateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DataPayable30Channel : Blackbird.Plugins.Plunet.DataPayable30Service.DataPayable30, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DataPayable30Client : System.ServiceModel.ClientBase<Blackbird.Plugins.Plunet.DataPayable30Service.DataPayable30>, Blackbird.Plugins.Plunet.DataPayable30Service.DataPayable30
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataPayable30Client() : 
                base(DataPayable30Client.GetDefaultBinding(), DataPayable30Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataPayable30Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataPayable30Client(EndpointConfiguration endpointConfiguration) : 
                base(DataPayable30Client.GetBindingForEndpoint(endpointConfiguration), DataPayable30Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataPayable30Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataPayable30Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataPayable30Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataPayable30Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataPayable30Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerArrayResult> searchAsync(string UUID, Blackbird.Plugins.Plunet.DataPayable30Service.SearchFilter_Payable SearchFilter)
        {
            return base.Channel.searchAsync(UUID, SearchFilter);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getCurrencyAsync(string UUID, int payablesID)
        {
            return base.Channel.getCurrencyAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setStatusAsync(string UUID, int Status, int payablesID)
        {
            return base.Channel.setStatusAsync(UUID, Status, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getStatusAsync(string UUID, int payablesID)
        {
            return base.Channel.getStatusAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceUnitListResult> getPriceUnit_ListAsync(string UUID, string languageCode, string service)
        {
            return base.Channel.getPriceUnit_ListAsync(UUID, languageCode, service);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineListResult> getPriceLine_ListAsync(string UUID, int payablesItemID)
        {
            return base.Channel.getPriceLine_ListAsync(UUID, payablesItemID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getResourceIDAsync(string UUID, int payablesID)
        {
            return base.Channel.getResourceIDAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> deletePriceLineAsync(string UUID, int payablesItemID, int priceLineID)
        {
            return base.Channel.deletePriceLineAsync(UUID, payablesItemID, priceLineID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineResult> updatePriceLineAsync(string UUID, int payablesItemID, Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineIN priceLineIN)
        {
            return base.Channel.updatePriceLineAsync(UUID, payablesItemID, priceLineIN);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceUnitResult> getPriceUnitAsync(string UUID, int PriceUnitID, string languageCode)
        {
            return base.Channel.getPriceUnitAsync(UUID, PriceUnitID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringArrayResult> getServices_ListAsync(string UUID, string languageCode)
        {
            return base.Channel.getServices_ListAsync(UUID, languageCode);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineResult> insertPriceLineAsync(string UUID, int payablesItemID, Blackbird.Plugins.Plunet.DataPayable30Service.PriceLineIN priceLineIN, bool createAsFirstItem)
        {
            return base.Channel.insertPriceLineAsync(UUID, payablesItemID, priceLineIN, createAsFirstItem);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getPayableIDAsync(string UUID, int itemID)
        {
            return base.Channel.getPayableIDAsync(UUID, itemID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getValueDateAsync(string UUID, int payablesID)
        {
            return base.Channel.getValueDateAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setValueDateAsync(string UUID, System.DateTime valueDate, int payablesID)
        {
            return base.Channel.setValueDateAsync(UUID, valueDate, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getInvoiceDateAsync(string UUID, int payablesID)
        {
            return base.Channel.getInvoiceDateAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setInvoiceDateAsync(string UUID, System.DateTime invoiceDate, int payablesID)
        {
            return base.Channel.setInvoiceDateAsync(UUID, invoiceDate, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getMemoAsync(string UUID, int payablesID)
        {
            return base.Channel.getMemoAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setMemoAsync(string UUID, int payablesID, string memo)
        {
            return base.Channel.setMemoAsync(UUID, payablesID, memo);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getPaidDateAsync(string UUID, int payablesID)
        {
            return base.Channel.getPaidDateAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setPaidDateAsync(string UUID, int payablesID, System.DateTime paidDate)
        {
            return base.Channel.setPaidDateAsync(UUID, payablesID, paidDate);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.BooleanResult> getIsExportedAsync(string UUID, int payablesID)
        {
            return base.Channel.getIsExportedAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getCompanyCodeAsync(string UUID, int payablesID)
        {
            return base.Channel.getCompanyCodeAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setIsExportedAsync(string UUID, int payablesID, bool isExported)
        {
            return base.Channel.setIsExportedAsync(UUID, payablesID, isExported);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getPaymentMethodAsync(string UUID, int payablesID)
        {
            return base.Channel.getPaymentMethodAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setCreditorAccountAsync(string UUID, string accountID, int payablesID)
        {
            return base.Channel.setCreditorAccountAsync(UUID, accountID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DoubleResult> getTotalNetAmountAsync(string UUID, int payablesID, int currencyTpe)
        {
            return base.Channel.getTotalNetAmountAsync(UUID, payablesID, currencyTpe);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> getPaymentCreatorResourceIDAsync(string UUID, int payablesID)
        {
            return base.Channel.getPaymentCreatorResourceIDAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setPaymentDueDateAsync(string UUID, int payablesID, System.DateTime dueDate)
        {
            return base.Channel.setPaymentDueDateAsync(UUID, payablesID, dueDate);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getExternalInvoiceNumberAsync(string UUID, int payablesID)
        {
            return base.Channel.getExternalInvoiceNumberAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setExternalInvoiceNumberAsync(string UUID, int payablesID, string externalNumber)
        {
            return base.Channel.setExternalInvoiceNumberAsync(UUID, payablesID, externalNumber);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getAccountStatementAsync(string UUID, int payablesID)
        {
            return base.Channel.getAccountStatementAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.TaxListResult> getInvoiceTaxTypesAsync(string UUID, int payablesID)
        {
            return base.Channel.getInvoiceTaxTypesAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getCreditorAccountAsync(string UUID, int payablesID)
        {
            return base.Channel.getCreditorAccountAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DoubleResult> getTotalTaxAmountAsync(string UUID, int payablesID, int currencyTpe, int taxType)
        {
            return base.Channel.getTotalTaxAmountAsync(UUID, payablesID, currencyTpe, taxType);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.DateResult> getPaymentDueDateAsync(string UUID, int payablesID)
        {
            return base.Channel.getPaymentDueDateAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> setAccountStatementAsync(string UUID, int payablesID, string accountstatement)
        {
            return base.Channel.setAccountStatementAsync(UUID, payablesID, accountstatement);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.StringResult> getExpenseAccountAsync(string UUID, int payablesID)
        {
            return base.Channel.getExpenseAccountAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.IntegerResult> insertPaymentItemAsync(string UUID, Blackbird.Plugins.Plunet.DataPayable30Service.PayableItemIN PaymentItemIN)
        {
            return base.Channel.insertPaymentItemAsync(UUID, PaymentItemIN);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.PayableItemResultList> getPaymentItemListAsync(string UUID, int payablesID)
        {
            return base.Channel.getPaymentItemListAsync(UUID, payablesID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> deletePaymentItemAsync(string UUID, int PaymentItemID)
        {
            return base.Channel.deletePaymentItemAsync(UUID, PaymentItemID);
        }
        
        public System.Threading.Tasks.Task<Blackbird.Plugins.Plunet.DataPayable30Service.Result> updatePaymentItemAsync(string UUID, Blackbird.Plugins.Plunet.DataPayable30Service.PayableItemIN PaymentItemIN, int PaymentItemID, bool enableNullOrEmptyValues)
        {
            return base.Channel.updatePaymentItemAsync(UUID, PaymentItemIN, PaymentItemID, enableNullOrEmptyValues);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataPayable30Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataPayable30Port))
            {
                return new System.ServiceModel.EndpointAddress("https://plunet-friend-blackbird.plunet.com/DataPayable30");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataPayable30Client.GetBindingForEndpoint(EndpointConfiguration.DataPayable30Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataPayable30Client.GetEndpointAddress(EndpointConfiguration.DataPayable30Port);
        }
        
        public enum EndpointConfiguration
        {
            
            DataPayable30Port,
        }
    }
}
